id: P52C3B25C
initial_creation_type: ocr
source_metadata:
  volumes:
    e68f5f4fa80b477db3987b3499556417:
      base_file: v040.txt
      image_group_id: I1PD95885
      title: ཀླུའི་དབང་ཕྱུག་རྒྱལ་པོའི་སྒྲུབ་ཐབས།
      total_pages: 1648
      volume_number: 40
